linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - gocyclo
    - gofmt
    - goimports
    - misspell
    - unconvert

linters-settings:
  gocyclo:
    min-complexity: 15
  gosec:
    excludes:
      - G104 # Audit errors not checked
  goimports:
    local-prefixes: github.com/project/backend

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec

run:
  timeout: 5m
  tests: true
