// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"github.com/project/backend/domain/entities"
)

type AuthPayload struct {
	User         *entities.User `json:"user"`
	AccessToken  string         `json:"accessToken"`
	RefreshToken string         `json:"refreshToken"`
}

type CreateLibraryCourseInput struct {
	Title          string              `json:"title"`
	Description    string              `json:"description"`
	Lessons        []*LessonInput      `json:"lessons"`
	Author         string              `json:"author"`
	Tags           []string            `json:"tags,omitempty"`
	Difficulty     entities.Difficulty `json:"difficulty"`
	EstimatedHours int                 `json:"estimatedHours"`
}

type CreateUserInput struct {
	Email    string `json:"email"`
	Name     string `json:"name"`
	Password string `json:"password"`
}

type ImportCoursesInput struct {
	Courses []*CreateLibraryCourseInput `json:"courses"`
}

type LessonInput struct {
	Title      string         `json:"title"`
	Content    string         `json:"content"`
	Order      int            `json:"order"`
	Sublessons []*LessonInput `json:"sublessons,omitempty"`
	Quiz       *QuizInput     `json:"quiz,omitempty"`
}

type LibraryCourseConnection struct {
	Courses []*entities.LibraryCourse `json:"courses"`
	Total   int                       `json:"total"`
	Page    int                       `json:"page"`
	Limit   int                       `json:"limit"`
	HasMore bool                      `json:"hasMore"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type PaginationInput struct {
	Page  *int `json:"page,omitempty"`
	Limit *int `json:"limit,omitempty"`
}

type Query struct {
}

type QuizInput struct {
	Questions []*QuizQuestionInput `json:"questions"`
}

type QuizQuestionInput struct {
	Question     string   `json:"question"`
	Options      []string `json:"options"`
	CorrectIndex int      `json:"correctIndex"`
	Explanation  *string  `json:"explanation,omitempty"`
}

type QuizResponseInput struct {
	QuestionID       string                    `json:"questionId"`
	UserAnswer       string                    `json:"userAnswer"`
	IsCorrect        bool                      `json:"isCorrect"`
	PointsEarned     int                       `json:"pointsEarned"`
	PointsPossible   int                       `json:"pointsPossible"`
	Confidence       *entities.ConfidenceLevel `json:"confidence,omitempty"`
	TimeTakenSeconds *int                      `json:"timeTakenSeconds,omitempty"`
}

type RegisterInput struct {
	Email    string `json:"email"`
	Name     string `json:"name"`
	Password string `json:"password"`
}

type StartCourseInput struct {
	LibraryCourseID string `json:"libraryCourseId"`
}

type SubmitQuizAttemptInput struct {
	CourseID       string               `json:"courseId"`
	QuizType       string               `json:"quizType"`
	QuizID         string               `json:"quizId"`
	Score          int                  `json:"score"`
	MaxScore       int                  `json:"maxScore"`
	TotalQuestions int                  `json:"totalQuestions"`
	CorrectCount   int                  `json:"correctCount"`
	Responses      []*QuizResponseInput `json:"responses"`
}

type TokenPayload struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
}

type UpdateLibraryCourseInput struct {
	Title          *string              `json:"title,omitempty"`
	Description    *string              `json:"description,omitempty"`
	Lessons        []*LessonInput       `json:"lessons,omitempty"`
	Author         *string              `json:"author,omitempty"`
	Tags           []string             `json:"tags,omitempty"`
	Difficulty     *entities.Difficulty `json:"difficulty,omitempty"`
	EstimatedHours *int                 `json:"estimatedHours,omitempty"`
}

type UpdateProgressInput struct {
	UserCourseID       string `json:"userCourseId"`
	Progress           int    `json:"progress"`
	CurrentLessonIndex *int   `json:"currentLessonIndex,omitempty"`
}

type UpdateUserInput struct {
	Name  *string `json:"name,omitempty"`
	Email *string `json:"email,omitempty"`
}

type UserConnection struct {
	Users   []*entities.User `json:"users"`
	Total   int              `json:"total"`
	Page    int              `json:"page"`
	Limit   int              `json:"limit"`
	HasMore bool             `json:"hasMore"`
}

type UserCourseConnection struct {
	Courses []*entities.UserCourse `json:"courses"`
	Total   int                    `json:"total"`
	Page    int                    `json:"page"`
	Limit   int                    `json:"limit"`
	HasMore bool                   `json:"hasMore"`
}
